---

sudo: required

language: python
python: 3.5

services:
  - docker

env:
  - TOX_ENV=py35

before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - travis_wait 45 make docker_build
  - make docker_run

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend